#!/usr/bin/python

import sys
import os
import glob

os.system("mkdir -p inst_output")

files = glob.glob('./src/micrortps_agent/*.cpp')
for name in files:
    # exclude unrelevant
    if ('PubSubTypes.cpp' in name or
        '_Subscriber.cpp' in name or
        '_Publisher.cpp' in name or
        'microRTPS_' in name or
        'RptsTopics.cpp' in name):
       continue

    file = open(name, 'r')
    outfilename = os.path.basename(name)
    outfile = open("./inst_output/" + outfilename, 'w')
    print("open file: " + name)
    dcdr_state = 0
    for line in file:
        if dcdr_state == 0:
            if ("void px4_msgs::msg::" in line and
                "::deserialize" in line):
                dcdr_state = 1
        elif dcdr_state == 1:
            if "{" in line:
                dcdr_state = 2
        elif dcdr_state == 2:
                outfile.write('    dcdr.jump(m_topic_id);\n')
                dcdr_state = 3

        outfile.write(line)

    file.close()
    outfile.close()

files = glob.glob('./src/micrortps_agent/*.h')
for name in files:
    # exclude unrelevant
    if ('PubSubTypes.h' in name or
        '_Subscriber.h' in name or
        '_Publisher.h' in name or
        'microRTPS_' in name or
        'RptsTopics.h' in name):
       continue

    file = open(name, 'r')
    outfilename = os.path.basename(name)
    outfile = open("./inst_output/" + outfilename, 'w')
    print("open file: " + name)
    dcdr_state = 0
    for line in file:
        if dcdr_state == 0:
            if "private:" in line:
                outfile.write('            eProsima_user_DllExport void setTopicId(uint8_t topic_id) { m_topic_id = topic_id; }\n')
                outfile.write('        private:\n')
                outfile.write('            uint8_t m_topic_id;\n')
                dcdr_state = 1
                continue

        outfile.write(line)

    file.close()
    outfile.close()

print("copy modified files into micrortps_agent folder")
os.system("cp ./inst_output/* ./src/micrortps_agent/")
os.system("rm -Rf ./inst_output")


